import React from "react"

const Hero = () => {
  return (
    <div className="min-h-[88vh] bg-black text-white">
      <div className="w-[85%] mx-auto flex">
        <div className="md:w-6/12 w-full mt-2">
          <div className="text-5xl font-medium">
            Connected Frontline Operations{` `}
            <span className="text-sky-500 font-bold">Grid.</span>
          </div>
          <div className="text-xl mt-12 w-[85%] text-gray-500">
            An integrated no-code data and operations management platform that
            brings together information generated by people, processes and
            machines to create connected experiences for the frontline workforce
            and real-time decision-making for management.
          </div>
          <button className="btn-grid mt-6">Sign up for a free trial</button>
        </div>
        <div className="w-6/12 mt-2 h-full">
          <img src="/grid-hero.jpg" className="h-full w-full" />
        </div>
      </div>
    </div>
  )
}

export default Hero
